<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css">
    <link rel="shortcut icon" href="assets/img/patas.png" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <title>DocePets</title>
</head>


<h1>Agendamentos pendentes...</h1>

<table class="table">
    <thead>
        <tr>
            <th scope="col">Nome</th>
            <th scope="col">Pet</th>
            <th scope="col">Serviço</th>
            <th scope="col">Data</th>
            <th scope="col">Hora</th>
            <th scope="col">Ações</th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($this->view->dados as $indice => $agendamento) {

        ?>
            <tr>
                <th scope="row"><?= $agendamento['nome_usuario'] . ' ' . $agendamento['sobrenome_usuario']; ?></th>
                <td><?= $agendamento['nomepet']; ?></td>
                <td><?= $agendamento['servicos']; ?></td>
                <td><?= $agendamento['data_agend']; ?></td>
                <td><?= $agendamento['horario']; ?></td>
                <td>
                    <a class="btn btn-secondary btn-sm" href="/editar_agendamento?id=<?= $agendamento['id_agendamento']; ?>" data-toggle="tooltip" data-placement="top" title=""><i class="bi bi-pencil-square"></i></a>
                    <a class="btn btn-danger btn-sm" href="?excluir=<?= $agendamento['id_agendamento']; ?>" data-toggle="tooltip" data-placement="top" title=""><i class="bi bi-x-square"></i></a>

                </td>
            </tr>
        <?php
        }
        ?>
    </tbody>
</table>







<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

</body>



</html>