<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="styles.css">
  <title>Agendamento de Pet Shop</title>
</head>
<body>
  <div class="container">
    <h1>Agendamento de Pet Shop</h1>
    <form>
      <label for="petName">Nome do Pet:</label>
      <input type="text" id="petName" name="petName" required>

      <label for="ownerName">Nome do Dono:</label>
      <input type="text" id="ownerName" name="ownerName" required>

      <!-- <label for="phone">Telefone:</label>
      <input type="tel" id="phone" name="phone" placeholder="Digite o telefone com DDD" oninput="formatPhoneNumber(this)"> -->

      <label for="tipo_servico">Tipo de Serviço:</label>
        <select id="tipo_servico" name="tipo_servico" required>
            <option value="Banho">Banho</option>
            <option value="Tosa">Tosa</option>
            <option value="Consulta Veterinária">Consulta Veterinária</option>
        </select>
        <br>

      <label for="appointmentDate">Data do Agendamento:</label>
      <input type="date" id="appointmentDate" name="appointmentDate" required>

      <label for="appointmentTime">Horário do Agendamento:</label>
      <input type="time" id="appointmentTime" name="appointmentTime" required>
      <br>
      <br>
      <br>
      <button type="submit">Agendar</button>

    </form>
    <br>
  </div>
</body>
</html>





