<div class="container-fluid px-4">
  <?php
  // dd($this->view->status);
  if (isset($this->view->status) && $this->view->status['status'] == "ERROR") {
  ?>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <strong>MENSAGEM: </strong> <?= $this->view->status['msg'] ?>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <?php
  }
  ?>

  <?php
  // dd($this->view->status);
  if (isset($this->view->status) && $this->view->status['status'] == "SUCCESS") {
  ?>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <strong>MENSAGEM: </strong> <?= $this->view->status['msg'] ?>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <?php
  }
  ?>


  <h1 class="section-title text-success">Agendamento</h1>
  <ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">Cuide do seu melhor amigo com apenas um clique | Faça uma agendamento</li>
  </ol>
  <div class="container">
    <form>
      <label for="nomepet">Nome do Pet:</label>
      <select id="nomepet" name="nomepet" required>
        <?php
        // Coloque aqui o código para recuperar os pets cadastrados pelo usuário
        // Substitua os valores de exemplo pelos valores reais do seu banco de dados
        $pets = array();

        foreach ($pets as $petId => $petNome) {
          echo "<option value='$petId>$petNome'</option>";
        }
        ?>
      </select>


      <label for="ownerName">Nome do Dono:</label>
      <input type="text" id="ownerName" name="ownerName" required>

      <select id="tipo_servico" name="tipo_servico" required>
        <option value="Banho">Banho</option>
        <option value="Tosa">Tosa</option>
        <option value="Consulta Veterinária">Consulta Veterinária</option>
      </select>
      <br>

      <label for="appointmentDate">Data do Agendamento:</label>
      <input type="date" id="appointmentDate" name="appointmentDate" required>

      <label for="appointmentTime">Horário do Agendamento:</label>
      <input type="time" id="appointmentTime" name="appointmentTime" required>
      <br>
      <br>
      <br>
      <button type="submit">Agendar</button>

    </form>
    <br>
  </div>
</div>