<?php 
use App\Models\TipoModel;
use App\Models\RacaModel;

?>
<div class="container-fluid px-4">

    <?php
    // dd($this->view->status);

    if (isset($this->view->status) && $this->view->status['status'] == "ERROR") {
    ?>
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <strong>MENSAGEM: </strong> <?= $this->view->status['msg'] ?>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    <?php
    }
    ?>

    <?php
    // dd($this->view->status);
    if (isset($this->view->status) && $this->view->status['status'] == "SUCCESS") {
    ?>
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <strong>MENSAGEM: </strong> <?= $this->view->status['msg'] ?>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    <?php
    }
    ?>

    <h1 class="section-title text-success">Perfil do Pet</h1>
    <br>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item active">Preencha o formulário com os dados do pet abaixo e clique em cadastrar</li>
    </ol>

    <form action="/salvar_pet" method="POST" enctype="multipart/form-data">
        <br>
        <label>Nome do pet</label>
        <input type="text" id="nomepet" name="nomepet" placeholder="Nome do pet" class="form-control mb-4 shadow rounded-0">
        <label>Data Nascimento Pet</label>
        <input type="date" id="nasc_data" name="nasc_data" placeholder="DD/MM/AAAA" class="form-control mb-4 shadow rounded-0">

        <label>Tipo Pet</label>
        <select name="id_pet" id="select-pets" data-test="select-pet-breed" class="form-control mb-4 shadow rounded-0">
            <option value="select-pets">Seu pet é um...</option>
            <?php foreach(TipoModel::listar() as $l) {?>
            <option value="<?= $l['id_pet'] ?>"><?= $l['descricao'] ?></option>
            <?php } ?>
        </select>

        <label>Raça do Pet</label>
        <select name="id_raca" id="select-pets" data-test="select-pet-breed" class="form-control mb-4 shadow rounded-0">
            <option value="select-pets">Raça do seu Pet</option>
            <?php foreach(RacaModel::listar() as $l) {?>
            <option value="<?= $l['id_raca'] ?>"><?= $l['descricao'] ?></option>
            <?php } ?>
            
        <label>Sexo do Pet: </label><br>
        <input name="genero" type="radio" id="radio-gender1" data-test="radio-pet-female" class="radio__RadioInput" value="FEMALE">
        <label for="radio-gender1" class="radio__Label">Fêmea</label>
        <input name="genero" type="radio" id="radio-gender2" data-test="radio-pet-male" class="radio__RadioInput" value="MALE">
        <label for="radio-gender2" class="radio__Label">Macho</label>
        <br>
        <label>Para mais atenção com o seu pet</label> 
        <input type="text" id="observacoes" name="observacoes" placeholder="Informações extras" class="form-control mb-4 shadow rounded-0">
        <div class="col-12 col-md-6 mb-3">
            <input class="btn btn-success" type="submit" value="Cadastrar" />
        </div>
    </form>
</div>
</div>