<div class="container contato">
    <div class="row">
        <div class="col-12">
            <h2 class="section-title text-success">Tem alguma dúvida?</h2>
            <h6>Preencha o formulário com os dados abaixo e clique em enviar.</h6>

            <form action="#">
                <input type="text" id="name" name="name" placeholder="Nome" class="form-control mb-4 shadow rounded-0">
                <input type="email" id="mail" name="mail" placeholder="E-mail" class="form-control mb-4 shadow rounded-0">
                <input type="text" id="subject" name="subject" placeholder="Assunto" class="form-control mb-4 shadow rounded-0">
                <textarea name="message" id="message" placeholder="Mensagem" class="form-control mb-4 shadow rounded-0"></textarea>
                <button type="submit" value="send" class="btn btn-success" onclick='swal("Good job!", "You clicked the button!", "success")'>Enviar</button>
            </form>
        </div>
    </div>
</div>