<link rel="stylesheet" href="assets/css/style.css">


<div class="container">
    <div class="row">
        <div class="col-12">
            <h2 class="section-title">Ficou com dúvida?</h2>
            <p>Nos conte as suas dúvidas aqui embaixo. Responderemos da melhor forma possível !!</p>

            <form action="#">
                <input type="text" id="name" name="name" placeholder="Nome" class="form-control mb-4 shadow rounded-0">
                <input type="email" id="mail" name="mail" placeholder="E-mail" class="form-control mb-4 shadow rounded-0">
                <input type="text" id="subject" name="subject" placeholder="Assunto" class="form-control mb-4 shadow rounded-0">
                <textarea name="message" id="message" placeholder="Mensagem" class="form-control mb-4 shadow rounded-0"></textarea>
                <button type="submit" value="send" class="btn">Enviar</button>
            </form>
        </div>
    </div>
</div>