

    <div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="assets/img/banner1.jpg" class="d-block w-100" width="800" height="400" role="img" alt="...">
    </div>
    <div class="carousel-item">
      <img src="assets/img/banner2.png" class="d-block w-100" width="800" height="400" role="img" alt="...">
    </div>
    <div class="carousel-item">
      <img src="assets/img/banner3.png" class="d-block w-100" width="800" height="400"  role="img" alt="...">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

     <!-- Modal -->
     <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
     <div class="modal-dialog">
         <div class="modal-content">
             <div class="modal-header">
                 <img src="assets/img/logo.jfif" width="100">
                 <button id="close-modal">X</button>
             </div>
             <div id="modal-body">
                <form>
                    <label for="Login">Login</label>
                    <input type="text" name="login" id="login" placeholder="login" required>

                    <label for="password">Senha</label>
                    <input type="password" name="password" id="password" placeholder="senha" required>

                    <button id="logar">Logar</button>
                </form>
            </div>
         </div>
     </div>
 </div>

 

 <div class="container-fluid ">
    <div class="row">
      <div class="col-lg-3 mb-3">
        <div class="card" style="width: 18rem;">
          <img src="assets/img/card2.webp" class="card-img-top" alt="...">
          <div class="card-body">
            <p class="card-text">Adote uma alegria na sua vida !!</p>
          </div>
        </div>
      </div>
  
      <div class="col-lg-3 mb-3">
        <div class="card" style="width: 18rem;">
          <img src="assets/img/card1.webp" class="card-img-top" alt="...">
          <div class="card-body">
            <p class="card-text"> Eles merecem Amor e Carinho !!</p>
          </div>
        </div>
      </div>
  
      <div class="col-lg-3 mb-3">
        <div class="card" style="width: 18rem;">
          <img src="assets/img/card3.webp" class="card-img-top" alt="...">
          <div class="card-body">
            <p class="card-text">Cada pet com sua personalidade !!</p>
          </div>
        </div>
      </div>

      <div class="col-lg-3 mb-3">
        <div class="card" style="width: 18rem;">
          <img src="assets/img/card6.png" class="card-img-top" alt="...">
          <div class="card-body">
            <p class="card-text">Seu Pet merece o melhor !!</p>
          </div>
        </div>
      </div>
    </div>
  </div>
  


