<!-- banner -->
<div class="banner__imagem">
    <img src="assets/img/pets.png" alt="Imagem em Tela Cheia" class="fullscreen-image">
</div>


<div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
		<div class="carousel-inner">
			<div class="carousel-item active">
				<img src="assets/img/2.png" class="d-block w-100" alt="...">
			</div>
			<div class="carousel-item">
				<img src="assets/img/3.png" class="d-block w-100" alt="...">
			</div>
			<div class="carousel-item">
				<img src="assets/img/4.png" class="d-block w-100" alt="...">
			</div>
			<div class="carousel-item">
				<img src="assets/img/5.png" class="d-block w-100" alt="...">
			</div>
		</div>
	</div>