<!-- banner -->
<div class="banner__imagem">
    <img src="assets/img/pets.png" alt="Imagem em Tela Cheia" class="fullscreen-image">
</div>


<div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
		<div class="carousel-inner">
			<div class="carousel-item active">
				<img src="assets/img/2.png" class="d-block w-100" alt="...">
			</div>
			<div class="carousel-item">
				<img src="assets/img/3.png" class="d-block w-100" alt="...">
			</div>
			<div class="carousel-item">
				<img src="assets/img/4.png" class="d-block w-100" alt="...">
			</div>
			<div class="carousel-item">
				<img src="assets/img/5.png" class="d-block w-100" alt="...">
			</div>
		</div>
	</div>



	<section id="quem-somos" class="quem-somos">
            <h3 class="quem-somos__titulo">Quem Somos</h3>
            <p class="quem-somos__descricao">Conheça a comunidade por trás da iniciativa</p>
            <div class="pessoas">
                <div class="pessoa">
                    <div class="pessoa__imagem pessoa__imagem--roberta"></div>
                    <span class="pessoa__nome">Roberta</span>
                    <span class="pessoa__funcao">Conteúdo</span>

                </div>

                <div class="pessoa">
                    <div class="pessoa__imagem pessoa__imagem--andreia"></div>
                    <span class="pessoa__nome">Andreia</span>
                    <span class="pessoa__funcao">Conteúdo</span>

                </div>

                <div class="pessoa">
                    <div class="pessoa__imagem pessoa__imagem--marcela"></div>
                    <span class="pessoa__nome">Marcela</span>
                    <span class="pessoa__funcao">Conteúdo</span>

                </div>



            </div>

        </section>