<div class="container login">
    <div class="row">
        <div class="col-6">
            <h2 class="section-title text-success" >Login</h2>
            <h8 >Para prosseguir, faça seu login</h8>

            <form class="docepets.usuário" method="post" action="/autenticar">
                <input type="email" id="email" name="email" placeholder="E-mail" class="form-control mb-4 shadow rounded-0">

                <input type="password" id="senha" name="senha" placeholder="Senha" class="form-control mb-4 shadow rounded-0">

                <button type="submit" value="dados" class="btn btn-success">Entrar</button>

                <hr>

                <div>
                    <a href="/usuario_novo" class="text-success">Criar conta</a>
                </div>


                <?php if ($this->view->login == 401) { ?>
                    <script>
                        swal({
                            title: "SORRY!",
                            text: "Email e/ou senha inválida.",
                            icon: "error",
                            button: "OK",
                        });
                    </script>
                <?php } ?>

                <?php if ($this->view->login == 403) { ?>
                    <script>
                        swal({
                            title: "HAHA!",
                            text: "Acesso negado.",
                            icon: "error",
                            button: "OK",
                        });
                    </script>
                <?php } ?>
            </form>
        </div>
    </div>
</div>