<link rel="stylesheet" href="assets/css/style.css">

<div class="container">
    <div class="row">
        <div class="col-6">
            <h2 class="section-title">DocePets - Login</h2>
            <p>Insira os seus dados de acesso para entrar.</p>

            <form class="user" method="post" action="/autenticar">
                <input type="email" id="email" name="email" placeholder="E-mail" class="form-control mb-4 shadow rounded-0">

                <input type="password" id="senha" name="senha" placeholder="Senha" class="form-control mb-4 shadow rounded-0">

                <button type="submit" value="dados" class="btn">Entrar</button>

                <hr>

                <div>
                    <a class="informativo" href="#">Esqueceu a senha?</a>
                </div>

                <div>
                    <a class="informativo" href="#">Criar conta</a>
                </div>

               


                <?php if ($this->view->login == 401) { ?>
                    <script>
                        swal({
                            title: "Error!",
                            text: "E-mail ou senha inválido!",
                            icon: "error",
                            button: "Ok",
                            });
                    </script>
                <?php } ?>

                <?php if ($this->view->login == 403) { ?>
                    <script>
                        swal({
                            title: "Error!",
                            text: "Acesso negado",
                            icon: "error",
                            button: "Ok",
                            });
                    </script>
                <?php } ?>


            </form>
        </div>
    </div>
</div>
