<section class="home">
  <div class="elementor-widget-container">

    <h1 class="section-title">>> Quem é a DocePets? <<</h1>

    <div class="spacer h10"></div>

    <br>
    <br>
    <br>
    <!-- <h3>
      <br>
      <strong class="section-title">Quem Somos?</strong>
    </h3> -->
    <p class="container">
    "🐾 Nos olhos brilhantes e no olhar sincero dos nossos queridos pets, encontramos um amor puro e incondicional que aquece nossos 
    corações. Eles nos entendem sem palavras, nos alegram nos momentos tristes e nos acompanham em cada jornada da vida. Cada patinha 
    que toca o chão é um lembrete constante de como o amor é capaz de transcender barreiras e unir almas de maneira única. Nossos pets
    são mais do que animais de estimação; são amigos fiéis, membros da família e fontes infinitas de alegria. Que possamos retribuir
    esse amor com cuidado, carinho e a dedicação que eles merecem. Afinal, é nos momentos compartilhados com eles que descobrimos o 
    verdadeiro significado de amor incondicional. ❤️❤️❤️" - Raquel e Thais
    </p>
    <p>
    "🐰E por isso a DocePets, veio para proporcionar uma vida mais doce e feliz para os nossos amigos peludos.
      Somos uma equipe especialistas dedicados a oferecer os melhores serviços para cuidar dos seus queridos pets.🐕
    </p>
    <p>
      Além disso, nossos profissionais são treinados e qualificados na área, tornando o banho do seu pet um momento
      tranquilo, agradável e seguro, tendo também a gestão de saúde e tratamentos diferenciados.😺🐱
    </p>
    <p>
      Nosso atendimento percorre por diversas etapas de uma consulta, como prevenção e diagnóstico.
      Sabemos que seu tempo é curto, mas queremos que você aproveite cada segundo que passar
      Por isso, a gente trata todos os pets com muita dedicação e respeito,
      para que nossas lojas, e serviços estejam à altura de proporcionar amor e cuidado.🐇
    </p>

    <p>
      Visite-nos hoje e proporcione ao seu pet a atenção que ele merece.

      Somos a DocePets, seu pet center de estimação! 🐾🐾🦴🐾🐾"
    </p>

  
</section>
</div>