<div class="container">
    <div class="row">
        <div class="col-12">
            <h2 class="section-title text-primary">Quem somos </h2>
            <p>Ter um animal de estimação é uma experiência verdadeiramente enriquecedora e repleta de benefícios.
                 Os pets, sejam eles cães, gatos, pássaros ou outros, desempenham um papel significativo em nossas vidas
                  e nos proporcionam companhia, alegria e amor incondicional.</p>
                  <p>Diante disso resolvemos criar a DOCEPETS, uma pequena empresa voltada somente para o bem estar do seu animalzinho.</p>
                
            </div>
            </div>
            </div>
