<!DOCTYPE html>
<html lang="pt-br">

<head>
	<meta charset="utf-8">
	<title><?= isset($this->view->title) ? $this->view->title : "DocePets"; ?></title>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">]
	<link rel="stylesheet" href="public/assets/css/style.css">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
	 integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
</head>

<body>
	<!-- header -->
	<header class="cabecalho">
        <nav class="navbar bg-custom fixed-top">
            <div class="container-fluid">
                <img class="logo" width="150" src="assets/img/logo.jfif" alt="logo">
                <ul class="menu__lista">
                    <li class="menu__item">
                        <a class="menu__link menu--ativo" href="/"><svg xmlns="http://www.w3.org/2000/svg" width="30"
                                height="30" fill="currentColor" class="bi bi-house-heart" viewBox="0 0 16 16">
                                <path d="M8 6.982C9.664 5.309 13.825 8.236 8 12 2.175 8.236 6.336 5.309 8 6.982Z" />
                                <path
                                    d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.707L2 8.207V13.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V8.207l.646.646a.5.5 0 0 0 .708-.707L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.707 1.5ZM13 7.207V13.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V7.207l5-5 5 5Z" />
                            </svg></a>
                    </li>

                    <li class="menu__item">
                        <a class="menu__link" href="/contato">Contato</a>
                    </li>

                    <li class="menu__item">
                        <a class="menu__link" href="/sobre_nos"><img width="30" src="assets/img/patas.png"> Quem somos</a>
                    </li>

                    <li class="menu__item">
                        <a class="menu__link" href="/nossas_lojas">Nossas Lojas</a>
                    </li>
                    <li class="menu__item">
                        <a class="menu__link" href="/servicos">Serviços pet</a>
                    </li>

                    <li class="menu__item--separador"></li>

                    <li class="menu__item">

				

						<?php

						use App\controllers\AuthController;

						if (AuthController::esta_logado()) {
						?>
							<li class="nav-item">
								<a class="nav-link text-dark btn btn-primary" href="/admin">Admin</a>
							</li>
						<?php
						} else {
						?>
							<li class="nav-item">
								<a class="nav-link text-dark btn btn-primary" href="/login">Entrar</a>
							</li>
						<?php
						}
						?>


					</ul>
				</div>
			</div>
		</nav>





		<!-- banner -->
		
		
		<!-- /banner -->


	</header>
	<!-- /header -->


	<!-- topics -->
	<section class="section">
		<?php $this->content(); ?>
	</section>
	<!-- /topics -->

	

	<!-- footer -->
	
<footer class="bd-footer footer">
 <div class="container-fluid ">
    <div class="row">
        <div class="col-lg-3 mb-3">
            <a class="d-inline-flex align-items-center mb-2" href="_" aria-label="DocePets"><img src="assets/img/logo.jfif" alt=""></a>

        </div>
        <div class="col-6 col-lg-2 mb-3">
            <h5>ALL</h5>
            <ul class="list-unstyled">
                <li class="mb-2"> <a href="#">Home</a></li>
                <li class="mb-2"> <a href="#">Contato</a></li>
                <li class="mb-2"><a href="#">Sobre Nos</a></li>
                <li class="mb-2"><a href="#">Locais</a></li>
            </ul>

        </div>

        <div class="col-6 col-lg-2 mb-3">
            <h5>ALL</h5>
            <ul class="list-unstyled">
                <li class="mb-2"> <a href="#">Home</a></li>
                <li class="mb-2"> <a href="#">Contato</a></li>
                <li class="mb-2"><a href="#">Sobre Nos</a></li>
                <li class="mb-2"><a href="#">Locais</a></li>
            </ul>

        </div>

        <div class="col-6 col-lg-2 mb-3">
            <h5>ALL</h5>
            <ul class="list-unstyled">
                <li class="mb-2"> <a href="#">Home</a></li>
                <li class="mb-2"> <a href="#">Contato</a></li>
                <li class="mb-2"><a href="#">Sobre Nos</a></li>
                <li class="mb-2"><a href="#">Locais</a></li>
            </ul>

        </div>

        <div class="col-6 col-lg-2 mb-3">
            <h5>ALL</h5>
            <ul class="list-unstyled">
                <li class="mb-2"> <a href="#">Home</a></li>
                <li class="mb-2"> <a href="#">Contato</a></li>
                <li class="mb-2"><a href="#">Sobre Nos</a></li>
                <li class="mb-2"><a href="#">Locais</a></li>
            </ul>

        </div>

    </div>
 </div>
</footer>
	
</body>

</html>