<!DOCTYPE html>
<html lang="pt-br">

<head>
	<meta charset="utf-8">
	<title><?= isset($this->view->title) ? $this->view->title : "DocePets"; ?></title>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
	<link rel="stylesheet" href="public/assets/css/style.css">
	<link rel="stylesheet" href="public/assets/css/rodape.css">
	<!-- <link rel="stylesheet" href="assets/cssl/style.css"> -->
	<link rel="stylesheet" href="assets/css/style.css">

	<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
</head>

<body class="p-0 m-0 border-0 position-absolute bd-example">
	<nav class="navbar navbar-expand-lg  bg-light w-100	">
		<div class="container-fluid">
			<img class="logo" src="assets/img/logo_1.png" alt="logo" >
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse d-flex justify-content-between " id="navbarSupportedContent">
				
				<ul class="navbar-nav me-auto mb-2 mb-lg-0">
					<li class="nav-item dropdown">
						<a class="nav-link active" aria-current="page" href="/">Home</a>
					</li>
					<li class="nav-item dropdown">
						<a class="nav-link" href="/contato">Contato</a>
					</li>

					<!-- <li class="nav-item dropdown z-3">
						<a class="nav-link" href="/agendamento">Agendamento</a>
					</li>
					<li class="nav-item dropdown z-3">
						<a class="nav-link" href="/cadastro_pet">Cadastro Pet</a>
					</li> -->
					
					<li class="nav-item">
						<a class="nav-link" href="/quem_somos">Quem somos</a>
					</li>
					<li class="menu__item">

						<!-- Button trigger modal -->
						<button type="button" class="btn" data-bs-toggle="modal" data-bs-target="#exampleModal"><a class="menu__link menu--ativo" href="/login"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart-fill" viewBox="0 0 16 16">
									<path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z" />
								</svg> Entrar</a>
						</button>


					</li>
				</ul>
			
			</div>
		</div>
	</nav>

	<!-- /header -->

		<!-- topics -->
		<section class="background">
			<?php $this->content(); ?>
		</section>

		<!-- /topics -->
<!-- footer -->

</main>
	<footer>
		<div id="footer_content">
			<div id="footer_contacts">
				<div id="footer_social_media">

					<a href="https://instagram.com/thaaa_fernanda?igshid=OGQ5ZDc2ODk2ZA==" class="footer-link" id="instagram">
					<i class="fa-brands fa-instagram"></i>
					</a>

					<a href="https://www.facebook.com/sincerodogs?mibextid=LQQJ4d" class="footer-link" id="facebook">
					<i class="fa-brands fa-facebook"></i>
					</a>

					<a href="https://wa.me/5565984657689?text=Ol%C3%A1%2C+tudo+bem%3F+Ficamos+muito+felizes+com+o+seu+contato%21+Como+a+DocePets+pode+te+ajudar+hoje%3F" class="footer-link" id="whatsapp">
					<i class="fa-brands fa-whatsapp"></i>
					</a>
				</div>
			</div>

		<ul class="footer-list">
			<li>
				<h3>Serviços</h3>
			</li>
			<li>
				<a href="/servicos" class="footer-link">Veterinária e estética</a>
			</li>
			<li>
				<a href="/servicos" class="footer-link">Banho e tosa</a>
			</li>
			<li>
				<a href="/servicos" class="footer-link">Consultas</a>
			</li>
		</ul>

		<ul class="footer-list">
			<li>
				<h3>Dúvidas</h3>
			</li>

			<li>
				<a href="/login" class="footer-link">DocePets@gmail.com</a>
			</li>
			<li>
				<a href="#" class="footer-link">3685-7624</a>
			</li>
			<li>
				<a href="#" class="footer-link">Política de privacidade</a>
			</li>
		</ul>
	
			
		<div id="footer_subscribe">
			<h3>Descrição</h3>

			<p>
                    A relação de amor e cumplicidade que temos com nossos bichinhos
                    de estimação é um vínculo único! 
                </p>
			<div id="input_group">
				<input type="email" id="email">
				<button>
				<i class="fa-regular fa-envelope"></i>
				</button>
			</div>
		</div>
	</div>

	<div id="footer_copyright">
		Copyright © 2023 - Docepets
	</div>

	</footer>

</body>

</html>