<!DOCTYPE html>
<html lang="pt-br">

<head>
	<meta charset="utf-8">
	<title><?= isset($this->view->title) ? $this->view->title : "Doce Pets"; ?></title>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

	<!-- ** CSS Plugins Needed for the Project ** -->

	<!-- Bootstrap -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

	<link rel="stylesheet" href="assets/cliente/plugins/bootstrap/bootstrap.min.css">
	
	<!-- themefy-icon -->
	<link rel="stylesheet" href="assets/cliente/plugins/themify-icons/themify-icons.css">
	<!--Favicon-->
	<link rel="shortcut icon" href="assets/img/rocket-takeoff-fill.svg" type="image/x-icon" />
	<!-- fonts -->
	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">
	<!-- Main Stylesheet -->
	<link href="assets/cliente/style.css" rel="stylesheet" media="screen" />
	<link rel="stylesheet" href="assets/css/style.css">

	<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
</head>

<body>
	<!-- header -->
	<header class="shadow-bottom sticky-top bg-white">
		<nav class="navbar navbar-expand-md">
			<div class="container">
				<a class="navbar-brand px-2" href="/"><img width="30" src="assets/img/patas.png">   DocePets</a>
				<button class="navbar-toggler border-0" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>

				<div class="collapse navbar-collapse text-center" id="navigation">
				<ul class="navbar-nav ml-auto">
						<li class="menu__item">
                        <a class="menu__link" href="/">Home</a>
                    </li>
					<ul class="navbar-nav ml-auto">
						
                        <a class="menu__link" href="/contato">Contato</a>
                    </li>

                    <li class="menu__item">
                        <a class="menu__link" href="/sobre_nos"> Quem somos</a>
                    </li>

                    <li class="menu__item">
                        <a class="menu__link" href="/nossas_lojas">Nossas Lojas</a>
                    </li>
                    <li class="menu__item">
                        <a class="menu__link" href="/servicos">Serviços pet</a>
                    </li>

					</ul>
				</div>
			</div>
		</nav>
	</header>
	<!-- /header -->

	<!-- contact -->
	<section class="section">
		<?php $this->content(); ?>
	</section>
	<!-- /contact -->

	<!-- footer -->
	<footer class="bd-footer footer">
 <div class="container-fluid ">
    <div class="row">
        <div class="col-lg-3 mb-3">
            <a class="d-inline-flex align-items-center mb-2" href="_" aria-label="DocePets"><img src="assets/img/logo.jfif" alt=""></a>

        </div>
        <div class="col-6 col-lg-2 mb-3">
		<h5>About</h5>
            <ul class="list-unstyled">
                <li class="mb-2"> <a href="/">Home</a></li>
                <li class="mb-2"> <a href="/contato">Contato</a></li>
                <li class="mb-2"><a href="/sobre_nos">Sobre Nos</a></li>
                <li class="mb-2"><a href="/nossas_lojas">Nossas Lojas</a></li>
            </ul>


        </div>

        <div class="col-6 col-lg-2 mb-3">
            <h5>ALL</h5>
            <ul class="list-unstyled">
                <li class="mb-2"> <a href="/servicos">Serviços</a></li>
                <li class="mb-2"> <a href="#">Contato</a></li>
                <li class="mb-2"><a href="#">Sobre Nos</a></li>
                <li class="mb-2"><a href="#">Locais</a></li>
            </ul>

        </div>

        <div class="col-6 col-lg-2 mb-3">
            <h5>ALL</h5>
            <ul class="list-unstyled">
                <li class="mb-2"> <a href="#">Home</a></li>
                <li class="mb-2"> <a href="#">Contato</a></li>
                <li class="mb-2"><a href="#">Sobre Nos</a></li>
                <li class="mb-2"><a href="#">Locais</a></li>
            </ul>

        </div>

        <div class="col-6 col-lg-2 mb-3">
            <h5>ALL</h5>
            <ul class="list-unstyled">
                <li class="mb-2"> <a href="#">Home</a></li>
                <li class="mb-2"> <a href="#">Contato</a></li>
                <li class="mb-2"><a href="#">Sobre Nos</a></li>
                <li class="mb-2"><a href="#">Locais</a></li>
            </ul>

        </div>

    </div>
 </div>
</footer>
	<!-- /footer -->

	<!-- ** JS Plugins Needed for the Project ** -->
	<!-- jquiry -->
	<script src="assets/cliente/plugins/jquery/jquery-1.12.4.js"></script>
	<!-- Bootstrap JS -->
	<script src="assets/cliente/plugins/bootstrap/bootstrap.min.js"></script>
	<!-- match-height JS -->
	<script src="assets/cliente/plugins/match-height/jquery.matchHeight-min.js"></script>
	<!-- Main Script -->
	<script src="assets/cliente/script.js"></script>
</body>

</html>