<div class="container-fluid px-4">
  <?php
  // dd($this->view->status);
// print_r($_SESSION);
  

use App\Models\AgendaModel;


  if (isset($this->view->status) && $this->view->status['status'] == "ERROR") {
  ?>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <strong>MENSAGEM: </strong> <?= $this->view->status['msg'] ?>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <?php
  }
  ?>

  <?php
  // dd($this->view->status);
  if (isset($this->view->status) && $this->view->status['status'] == "SUCCESS") {
  ?>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <strong>MENSAGEM: </strong> <?= $this->view->status['msg'] ?>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <?php
  }
  ?>


  <h1 class="section-title text-success">Agendamento</h1>
  <ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">Cuide do seu melhor amigo com apenas um clique | Faça um agendamento</li>
  </ol>

  <form action="/salvar_agenda" method="POST" enctype="multipart/form-data">
    <br>
    <label for="usuario_id" >Nome do Dono:
      <b><?php echo $_SESSION['nome']; ?> <?php echo $_SESSION['sobrenome']; ?></b>
      
    </label>
    <br>
    <br>
    <label for="nomepet">Pet</label>
    <select id="nomepet" name="pet_id" class="form-control mb-4 shadow rounded-0" required>
      <option value="" disabled selected>Escolha seu pet</option>
      <?php foreach (AgendaModel::listar() as $l) { ?>
        <option value="<?= $l['id_pet_cad'] ?>"><?= $l['nomepet'] ?>
        <?php } ?>
        </option>
    </select>
    <label>Serviços:</label>
    <select name="servicos" id="servicos" data-test="select-pet-breed" class="form-control mb-4 shadow rounded-0" required>
      <option value="" disabled selected>Escolha um serviço</option>
      <option value="banho">Banho</option>
      <option value="tosa">Banho e Tosa</option>
      <option value="consulta_veterinaria">Consulta Veterinária</option>
    </select>
    <label for="data_agend">Data do Agendamento:</label>
    <input type="date" id="data_agend" name="data_agend" class="form-control mb-4 shadow rounded-0" required>
    <label for="horario">Horário do Agendamento:</label>
    <input type="time" id="horario" name="horario" class="form-control mb-4 shadow rounded-0" required>

    <div class="col-12 col-md-6 mb-3">

      <input type="hidden" name="usuario_id" value="<?= $_SESSION['id_usuario'];?>"   />
      <input class="btn btn-success" type="submit" value="Agendar" />
    </div>
  </form>

</div>
</div>