
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css">
    <link rel="shortcut icon" href="assets/img/patas.png" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <title>Editar Agendamento</title>
</head>

<body>
    <h1>Editar Agendamento</h1>

    <?php
    // Verifique se o parâmetro 'id' está definido na URL

use App\Models\AgendaModel;

    if (isset($_GET['id_agendamento'])) {
        $id_agendamento = $_GET['id_agendamento'];

        // Carregue os detalhes do agendamento para preencher o formulário
        // (Você deve implementar esta lógica usando a classe AgendaModel)
        $agenda = new AgendaModel($db);
        $agenda->__set("id_agendamento", $id_agendamento);
        $agendamento = $agenda->autenticar(); // Substitua por seu método para carregar detalhes

        if ($agendamento) {
            ?>
            <form action="processar_atualizacao.php" method="POST">
                <input type="hidden" name="id_agendamento" value="<?= $agendamento->id_agendamento; ?>">

                <!-- Campos editáveis -->
                <label for="data_agend">Data:</label>
                <input type="date" name="data_agend" value="<?= $agendamento->data_agend; ?>"><br>

                <label for="horario">Horário:</label>
                <input type="time" name="horario" value="<?= $agendamento->horario; ?>"><br>

                <label for="usuario_id">ID do Usuário:</label>
                <input type="text" name="usuario_id" value="<?= $agendamento->usuario_id; ?>"><br>

                <label for="pet_id">ID do Pet:</label>
                <input type="text" name="pet_id" value="<?= $agendamento->pet_id; ?>"><br>

                <label for="servicos">Serviços:</label>
                <input type="text" name="servicos" value="<?= $agendamento->servicos; ?>"><br>

                <input type="submit" value="">
            </form>
        <?php
        } else {
            echo "Agendamento não encontrado.";
        }
    } else {
        echo "ID do agendamento não foi especificado na URL.";
    }
    ?>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</body>

</html>
